public enum TokenType {
    NUMBER,
    IDENTIFIER,
    EQUALS,
    BINARY_OPERATOR,
    OPEN_PAREN,
    CLOSE_PAREN,
    OPEN_CURLY,
    CLOSE_CURLY,
    OPEN_SQUARE,
    KEYWORD,
    CLOSE_SQAURE,
    VAR,
}
